#!/bin/bash
> 'result_M_1.csv'
> 'result_N_1.csv'
> 'result_K_1.csv'

if [ -n "$1" ]
then 
for ((i = 1; i <= $1 ;i++))
do
k=$(($i * 16))
./c.out 64 64 $k >> 'result_K_1.csv'
done
for ((i = 1; i <= $1 ;i++))
do
k=$(($i * 16))
./c.out 64 $k 64 >> 'result_N_1.csv'
done
for ((i = 1; i <= $1 ;i++))
do
k=$(($i * 16))
./c.out $k 64 64 >> 'result_M_1.csv'
done
else
./c.out
fi
